version: "3"

services:
  nginx:
    image: nginx:1.17.8
    ports:
      - "80:80"
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./server:/var/www
    links:
      - app
      
  app:
    build: "./server"
    ports:
      - 9000:9000
    volumes:
      - ./server:/var/www
    depends_on:
      - db
    links:
      - db    

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: contact
    ports:
      - 5432:5432
    volumes:
      - ./config/db/data:/var/lib/postgresql:z
      - ${PWD}/config/db:/docker-entrypoint-initdb.d    

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db

  # composer:
  #   image: composer:latest
  #   container_name: composer
  #   command: "composer install"
  #   volumes:
  #     - ./server:/var/www
  #   working_dir: /var/www
  #   links:
  #    - server
# volumes:
#   pgdata:  