version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: server
    ports:
      - 8000:8000
    volumes:
      - ./app:/etc/nginx/conf.d
      - ./app:/var/www
    links:
      - app
  app:
    build: "./app"
    container_name: app
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www
    depends_on:
      - db
    links:
      - db    

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: contact
    ports:
      - 5432:5432
    volumes:
      - ./config/db/data:/var/lib/postgresql:z
      - ${PWD}/config/db:/docker-entrypoint-initdb.d    
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
  composer:
    image: composer:latest
    container_name: composer
    command: "composer install"
    volumes:
      - ./app:/var/www    
    working_dir: /var/www
    links:
     - app
# volumes:
#   pgdata:  