<!DOCTYPE html>
<html lang="en">
<head>

 <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 
    <title><?php echo $title; ?></title>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
 <div class="container-fluid  d-flex justify-content-center">
  <div class="navbar-header"> 
    <ul>
        <li><a href="/">Index</a></li>
        <li><a href="/insert">Insert Contacts</a></li>
    </ul>
  </div>  
 </div>
</nav>

    
<?php include($viewName); ?>

</body>
</html> 