
<form action="", method="POST">
  <label for="name">Name:</label><br>
  <input value="<?php echo $name; ?>" id="name" name="name"><br>
  <label for="email">email:</label><br>
  <input value="<?php echo $email; ?>" type="email" id="email" name="email"><br>
  <label for="telefone">telefone:</label><br>
  <input value="<?php echo $telefone; ?>" id="telefone" name="telefone">
  <button type="submit">Enviar</button>
</form>