<?php foreach ($contacts as $contact) { ?>

<div class='card mt-4 container-fluid d-flex justify-content-center' style='width: 18rem;'>
    <div class='card-body'>
        <h5 class='card-title'><?php echo $contact["name"] ?></h5>
        <h6 class='card-subtitle mb-2 text-muted'><?php echo $contact["telefone"] ?></h6>
        <p class='card-text'><?php echo $contact["email"] ?></p>

    </div>

</div>
<div class='container-fluid  d-flex justify-content-center'>
            <a class='btn btn-danger' href='\delete?id=<?php echo $contact["contact_id"]?>'>Delete</a>
            <br>
            <a class='btn btn-warning' href='\edit?id=<?php echo $contact["contact_id"]?>'>Edit</a><br>
        </div>
<?php } ?>